### ISSUE TITLE
Example to work with

### ISSUE THREAD

**Issue by PAk-CatchFire** [machx0r/CCSWE-500px-API#1]
Hello.
 I am checking your C# implementation of the API and I think it is great!!

However I am new to C# and I would like to ask you a couple of questions:

-I am trying to do the auth example but if I use the provided example, the internal webbrowser wants to save a http_500_webOC HTML file throwing a HTTP 500 Internal Server Error.

 On the other hand, if I use an external webbrowser the 500px website answers with a "500 Internal Server Error". My commands are:
string url = _service.GetAuthorizeRequestTokenUrl(_requestToken);
 System.Diagnostics.Process.Start(url);
- Would you have a simple example to use the library?

Thank you for your time and help.
Best regards

**Comment by CoryCharlton** [comment]
I just validated the example provided on the main page of this project still works. I would start by confirming that the OAuthToken you receive from the `GetRequestToken()` method is valid (has both a `Secret` and `Token` specified).

Not directly related but you will probably need to update the registry to set the browser version for the internal `WebBrowser` control as 500px is rejecting older browsers now. These links will provide some insight:

https://stackoverflow.com/questions/10402813/wpf-webbrowser-browser-version
https://msdn.microsoft.com/en-us/library/ee330730%28v=vs.85%29.aspx#browser_emulation
http://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version

**Comment by PAk-CatchFire** [comment]
Thank you Cory!
You are right. I had to generate a new secret and key in 500px for this app and Auth worked like a charm!!

Now that I am authenticated, for example how can I get a list of pictures or check my commented pictures?

Do you have any small example of code? This project rocks!!

**Comment by CoryCharlton** [comment]
The `FiveHundredPxService.GetPhotos(IPhotoFilter filter, int page = 1, int resultsPerPage = 100)` method can be used to retrieve photos. To retrieve all your photos you would do something like this:

```
var getUserResponse = await _fiveHundredPxService.GetCurrentUser();
var photoFilter = new PhotoFilter(getUserResponse.User.Id);

var response = await _fiveHundredPxService.GetPhotos(photoFilter, 1, 100);
foreach (var photo in response.Photos)
{
    // Store the photos for the current page in a List<Photo> or something
}

if (response.TotalPages > 1)
{
    for (var i = 2; i <= response.TotalPages; i++)
    {
        response = await _fiveHundredPxService.GetPhotos(photoFilter, i, 100);
        foreach (var photo in response.Photos)
        {
            // Store the photos for the current page in a List<Photo> or something
        }
    }
}
```

The `PhotoFilter` class controls all the filtering to the `GetPhotos` call.

**Comment by PAk-CatchFire** [comment]
Thank you again Cory.
Now everything you told me is working fine, I can get my photos from the list and get the LIKES and FAVS from them, but I don't know how to get the comments or post a comment to them.

There is not any function for this in the Photo class. How can I get that?

The library works amazingly!!

Regards

**Comment by CoryCharlton** [comment]
@frasalyu currently I have not implemented any functionality related to comments as it was not required for my immediate project. I'll get around to it eventually but if you need it sooner feel free to fork the project. I'm always happy to review any pull requests if you want to contribute back.

If you do decide to implement comment functions here are some URLs that will help:

[GET Comments for a Photo](https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos_id_comments.md)
[POST Comment to a Photo](https://github.com/500px/api-documentation/blob/master/endpoints/photo/POST_photos_id_comments.md)
[POST Reply to existing Comment](https://github.com/500px/api-documentation/blob/master/endpoints/comments/POST_comments_id_comments.md)

**Comment by PAk-CatchFire** [comment]
Thank you Cory.

I have found what I think it is a bug, if you use the **FavoritePhoto POST function, you get a 401 Unathorized error**.
Inside the function, AccessToken has the secret and the Token values correctly (veryfier is null).

The funny thing is that Authentication works perfectly now and I can get all my photos from the API once I am Authorized.

On the other hand, to post a comment, I am getting a 400 error because the body of the POST message is not specified. I am assuming to use the Post<T> task in the library, but I don't know how to write the body.

**Edited:** If i pass the body in the url, I get the same 401 Unathorized response. I think it is something related to the service, but I don't know what is.

Regards

**Comment by PAk-CatchFire** [comment]
Hello again Cory.

If you have some time, please check also the LikePhoto function.

Maybe is something with the POST functions and how the OAuth is managed. By the way, I am using a WindowsForm project.

Thank you

**Comment by PAk-CatchFire** [comment]
Hello again Cory, the comment part is done!

But I am still strugling with the FavoritePhoto and LikePhoto functions you provided?
Are they working for you?

Thank you

**Comment by CoryCharlton** [comment]
@frasalyu the `FavoritePhoto(long photoId)` and `LikePhoto(long photoId)` functions do work for me. I use them heavily in the application I created this project for. I would ensure that you you are fully authenticated and using an AccessToken and not a RequestToken. In my application I only go through the authentication process once and then I store the AccessToken's `Token` and `Secret` for reuse.

**Comment by PAk-CatchFire** [comment]
Thank you again for your help and time, Cory.

Yes, I am doing exactly that. I am fully authenticated in a internal webbrowser control,  and keeping the AccessToken as well (not the requestToken).
If I check the currentuser() id, it is mine, but when I try to use the LikePhoto function (or any other POST method) I get the 401 response.

I am using a standard WindowsForm project.
Is it necessary to set any special property in the project? Unicode, UTF-8, etc...

Regards

**Comment by PAk-CatchFire** [comment]
BTW Cory, forgot to mention that the project file in the original ZIp file, throws an error because of this line:

< Import Project="....\Build\Microsoft.TextTemplating.targets"  />

Regards

**Comment by PAk-CatchFire** [comment]
Hello. 
I have created a Winforms simple example for testing the API.
https://github.com/frasalyu/CCSWE-500px-API-and-sample

 In the example I am Authenticating my user and liking & Faving a photo.
I am getting the 401 Unauthorised response after login in every post request (Like and Favorite). Could you give it a try?

I think I am using the API wrapper properly.

Thank you.

**Comment by CoryCharlton** [comment]
Interesting... I checked out your sample and the code looks good but I get a 401. Went back to my application and re-tested the liking/favoriting photos and I'm now getting a 401 unauthorized as well. However the other functionality (ie: adding/removing friends) still works. Something must have changed on the 500px API side. I'll try and see if I can figure it out.

**Comment by PAk-CatchFire** [comment]
Thank you Cory.
I was going crazy because of the 401. I couldn't find the cause, so I will wait for your answer.
Regards

**Comment by CoryCharlton** [comment]
Just a quick update on this. I've created an issue in the 500px API Documentation project: https://github.com/500px/api-documentation/issues/167

Other people are also experiencing the error but unfortunately 500px has not yet responded to the issue.

**Comment by CoryCharlton** [comment]
Never got a response from 500px on this one and since they recently decided to shutdown their API I'm going to archive this repository.
